parameters:
#    wanasni_avis.example.class: Wanasni\AvisBundle\Example

services:
#    wanasni_avis.example:
#        class: %wanasni_avis.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
