parameters:
#    wanasni_admin.example.class: Wanasni\AdminBundle\Example

services:
#    wanasni_admin.example:
#        class: %wanasni_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
